---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile_local.erb

provisioner:
  name: ansible_playbook
  hosts: ssh_servers
  sudo_command: sudo -E -H
  role_name: ssh-server
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  ansible_verbosity: warn


transport:
  max_ssh_sessions: 4


verifier:
  name: shell


suites:
  - name: defaults
    provisioner:
      playbook: tests/defaults.yml
      idempotency_test: true
    verifier:
      command: PLAYBOOK=tests/defaults.yml bundle exec rspec -c -I serverspec

  - name: gen-keys
    provisioner:
      playbook: tests/gen-keys.yml
      idempotency_test: false
    verifier:
      command: PLAYBOOK=tests/gen-keys.yml bundle exec rspec -c -I serverspec


platforms:
  - name: centos-7
    driver_config:
      box: bento/centos-7.2
      box_url: https://atlas.hashicorp.com/bento/boxes/centos-7.2

  - name: debian-8
    driver_config:
      box: bento/debian-8.6
      box_url: https://atlas.hashicorp.com/bento/debian-8.6

  - name: ubuntu-1404
    driver_config:
      box: bento/ubuntu-14.04
      box_url: https://atlas.hashicorp.com/bento/ubuntu-14.04

  - name: ubuntu-1604
    driver_config:
      box: bento/ubuntu-16.04
      box_url: https://atlas.hashicorp.com/bento/ubuntu-16.04
